name: Test Report

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  report:
    runs-on: 'ubuntu-20.04'
    steps:
    - run: echo '${{ toJSON(github) }}'
    - uses: dorny/test-reporter@artifacts-support
      with:
        artifact: /test-results-(.*)/
        name: Test Report $1
        path: '**/TestResults/*.trx'
        reporter: dotnet-trx
        list-tests: failed
